trigger:
- master

strategy:
  matrix:
    windows:
      imageName: 'windows-2019'
      python2: 'python2'
      python3: 'python'
      pip_cache_dir: C:\Users\VssAdministrator\AppData\Local\pip\cache

pool:
  vmImage: $(imageName)

steps:
- script: $(python2) --version
- script: $(python3) --version
- script: $(python3) -u -c "import sys; sys.stderr.write('written ' + str(sys.stdout.write(b'x'*131072)) + ' bytes\n')" > NUL
- script: $(python2) -u -c "import sys; sys.stderr.write('written ' + str(sys.stdout.write(b'x'*131072)) + ' bytes\n')" > NUL
